# Generated by Django 5.2.7 on 2025-10-24 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating_votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
